/**
 * EJP — Spanish / English language toggle
 * Usage: add data-i18n="key" to any translatable element.
 *        add data-i18n-placeholder="key" to inputs that need a translated placeholder.
 * The Español/English button must have class="js-lang-toggle".
 * Language preference is persisted in localStorage under "ejp_lang".
 */
(function () {
  var STORAGE_KEY = 'ejp_lang';

  // Spanish translations only — English is captured live from the DOM on first load.
  var es = {
    // ── Shared header ─────────────────────────────────────────────
    'header-tagline':        'Un Programa del Fondo de Capacitación y Empleo de 1199SEIU',
    'nav-funds-resources':   'Fondos y Recursos',
    'nav-fund-healthcare':   'Atención Médica',
    'nav-fund-pension':      'Pensión y Jubilación',
    'nav-fund-training':     'Capacitación y Empleo',
    'nav-fund-childcare':    'Cuidado Infantil y Servicios Juveniles',
    'nav-training-education':'Capacitación y Educación',
    'nav-te-precollege':     'Programas Pre-Universitarios',
    'nav-te-college':        'Programas Universitarios',
    'nav-te-continuing':     'Educación Continua',
    'nav-te-certifications': 'Certificaciones Ocupacionales',
    'nav-te-homecare':       'Capacitación para Trabajadores de Cuidado Domiciliario',
    'nav-te-rn':             'Capacitación para Enfermeras Registradas',
    'nav-employment':        'Empleo',
    'nav-job-seekers':       'Para Buscadores de Empleo',
    'nav-employers':         'Para Empleadores',
    'nav-cpt':               'Para CPT',
    'nav-events':            'Eventos',
    'nav-contact':           'Contacto',
    'nav-citizenship':       'Ciudadanía e Inglés',
    'nav-cit-program':       'Programa de Ciudadanía',
    'nav-cit-esol':          'ESOL',
    'nav-member-resources':  'Recursos para Miembros',
    'nav-mytef':             'Mi TEF',
    'logo-sub':              'Empleo y Colocación Laboral',
    'search-placeholder':    'Buscar en EJP...',
    // ── Shared footer ─────────────────────────────────────────────
    'footer-brand-sub':      'Empleo y Colocación Laboral',
    'footer-funds':          'Fondos 1199SEIU',
    'footer-privacy':        'Política de Privacidad',
    'footer-terms':          'Términos de Uso',
    'footer-a11y':           'Accesibilidad',
    'footer-copy':           '© 2026 Fondo de Capacitación y Empleo 1199SEIU. Todos los derechos reservados.',
    // ── MyTEF modal (injected by nav.js) ──────────────────────────
    'mytef-modal-title':     'Portal Mi TEF',
    'mytef-modal-body':      'Accede a tus registros de capacitación, inscripciones, solicitudes, currículum y estado de reembolsos — todo en el portal seguro myTEF.',
    'mytef-modal-li-1':      'Inscríbete en clases y programas de capacitación',
    'mytef-modal-li-2':      'Solicita oportunidades de avance profesional',
    'mytef-modal-li-3':      'Sube y administra tu currículum',
    'mytef-modal-li-4':      'Consulta reembolsos de matrícula y gastos',
    'mytef-modal-cta':       'Ir al Portal Mi TEF →',
    'mytef-modal-footnote':  'Serás llevado al portal seguro de miembros de 1199SEIU TEF para iniciar sesión.',
    // ── index.html ────────────────────────────────────────────────
    'index-hero-kicker':     'Su Socio en el Empleo en Salud',
    'index-hero-h1-1':       'Centro de Empleo y',
    'index-hero-h1-2':       'Ubicación Laboral',
    'index-hero-subtitle':   'Construimos carreras.',
    'index-hero-deck':       'Como parte de 1199SEIU, ayudamos a los buscadores de empleo a construir carreras duraderas y a los empleadores a formar equipos más fuertes desarrollando una fuente de puestos disponibles y candidatos calificados.',
    'index-hero-btn-primary':   'Buscando Trabajo →',
    'index-hero-btn-secondary': 'Busco Contratar →',
    'index-cpt-strong':      '¿Completando tu capacitación CPT?',
    'index-cpt-span':        'Tu equipo de servicios está listo para ayudarte a dar los próximos pasos.',
    'index-cpt-btn':         'Empieza Aquí →',
    'index-returning-body':  'Qué bueno verte de nuevo. EJP está aquí cuando estés listo — ya sea para conocer más sobre tus beneficios sindicales o mantenerte conectado con lo que está pasando.',
    'index-returning-btn1':  'Conoce los Beneficios de Membresía →',
    'index-returning-btn2':  'Mantente en Contacto',
    'index-services-kicker': 'Lo Que Hacemos',
    'index-services-h2':     'Apoyando el Empleo en Salud',
    'index-services-intro':  'Ya sea que estés buscando tu próximo rol o tratando de cubrir uno, EJP apoya a buscadores de empleo y empleadores por igual para crear una fuerza laboral donde el talento y la oportunidad en salud se alinean de manera fluida.',
    'index-svc-1-h3':        'Centralizar Empleos de Salud',
    'index-svc-1-p':         'EJP reúne ofertas de empleo de cientos de instalaciones asociadas en un portal fácil de usar para que puedas revisar oportunidades que se ajusten a tu perfil.',
    'index-svc-1-link':      'Para Buscadores de Empleo →',
    'index-svc-2-h3':        'Asociarse con Empleadores',
    'index-svc-2-p':         'EJP se asocia con empleadores de salud en toda Nueva York para entender sus necesidades de personal y conectarlos con candidatos calificados en el grupo de talentos de EJP.',
    'index-svc-3-h3':        'Abogar por los Trabajadores de Salud',
    'index-svc-3-p':         'Como parte de 1199SEIU, EJP trabaja activamente con instalaciones de salud para apoyar el desarrollo de la fuerza laboral en toda Nueva York. Puede que no siempre nos veas, pero estamos aquí trabajando en tu nombre.',
    'index-svc-2-link':      'Para Empleadores →',
    'index-svc-3-link':      'Conoce la Membresía de 1199 →',
    'index-about-h2':        'Historias de Éxito',
    'index-about-mission-p':   'El Centro de Empleo y Ubicación Laboral se dedica a ayudar a los buscadores de empleo a construir carreras duraderas y a los empleadores a formar equipos más fuertes a través de servicios de carrera personalizados y asociaciones directas con empleadores.',
    'index-about-stories-h3':  'Historias de Éxito',
    'index-pillar-1-h4':     'Colaborar',
    'index-pillar-1-p':      'Asociándonos con empleadores, programas de capacitación y sistemas de apoyo sindical',
    'index-pillar-2-h4':     'Empoderar',
    'index-pillar-2-p':      'Dando a los buscadores de empleo las herramientas, preparación y confianza para triunfar',
    'index-pillar-3-h4':     'Innovar',
    'index-pillar-3-p':      'Modernizando la colocación de la fuerza laboral en salud a través de la tecnología',
    'index-pillar-4-h4':     'Impacto',
    'index-pillar-4-p':      'Resultados medibles — colocaciones, retención, crecimiento profesional',
    'index-faq-kicker':      'Preguntas Frecuentes',
    'index-faq-h2':          'Preguntas Frecuentes',
    'index-faq-q1':          '¿Qué es EJP?',
    'index-faq-a1':          'El Centro de Empleo y Ubicación Laboral es una división del Fondo de Capacitación y Empleo de 1199SEIU dedicada a construir una fuerza laboral de salud sólida. EJP aprovecha nuestras alianzas con líderes sindicales y gerencia para crear éxito medible en reclutamiento y colocación mientras empodera a los buscadores de empleo a alcanzar carreras satisfactorias cerrando brechas laborales e impulsando soluciones innovadoras de reclutamiento.',
    'index-faq-q2':          '¿Quién califica para servicios de carrera de EJP?',
    'index-faq-a2':          'Actualmente, solo los participantes del Programa de Capacitación en Carreras Profesionales (CPT) reciben servicios completos de carrera a través de EJP, incluyendo asistencia con currículum, asesoramiento de carrera, preparación para entrevistas y apoyo de colocación laboral.\n\nLos participantes que no son de CPT aún pueden usar EJP para explorar puestos de salud disponibles y enviar su currículum a posiciones que coincidan con sus criterios.',
    'index-faq-q3':          '¿Enviar mi currículum a través de EJP me garantiza un trabajo?',
    'index-faq-a3':          'Ya seas participante de CPT o no, enviar tu currículum solo no garantiza que obtengas el trabajo al que apliques.\n\nPara buscadores de empleo que no son de CPT, no hay garantía de que recibirás respuesta de los trabajos a los que apliques ni un plazo garantizado para ser contactado. Una vez que envíes tu información, se te notificará si un trabajo está disponible que coincida con tus criterios y calificaciones.',
    'index-faq-q4':          '¿Cuáles son los beneficios de buscar trabajo a través de EJP?',
    'index-faq-a4':          'EJP trabaja de la mano con empleadores en todo el estado de Nueva York para colocar candidatos calificados en empleos de calidad.\n\nAdemás de aprovechar los beneficios de nuestras relaciones con empleadores, los buscadores de empleo que encuentren empleo a través de EJP estarán conectados a buenos empleos sindicales a través de 1199SEIU.',
    'index-faq-q5':          '¿Qué es 1199SEIU?',
    'index-faq-a5':          'Somos un sindicato de trabajadores de salud. Trabajamos en las industrias de atención domiciliaria, hospitales y hogares de ancianos, así como en farmacias, clínicas independientes y otros entornos de salud. Con más de 400,000 miembros en el estado de Nueva York, Massachusetts, Nueva Jersey, Florida, Maryland y el Distrito de Columbia, somos el sindicato local más grande del mundo.\n\nSer parte de 1199SEIU significa ser parte de una familia que se asegurará de que nunca tengas que luchar solo por tus derechos en el lugar de trabajo.',
    'index-faq-q6':          'Si ya soy miembro de 1199SEIU pero no soy participante de CPT, ¿puedo obtener apoyo de EJP?',
    'index-faq-a6':          'Los miembros existentes de 1199 pueden acceder a apoyo de carrera a través del portal MyTEF. A través de MyTEF, los miembros pueden acceder a servicios de apoyo de carrera, solicitar asesoramiento, gestionar sus beneficios y mucho más.',
    'index-faq-q7':          '¿Cómo publican los empleadores roles a través de EJP?',
    'index-faq-a7':          'Los proveedores de salud asociados pueden enviar vacantes directamente a EJP para conectarse con candidatos calificados y motivados. Si aún no eres socio, contáctanos para conocer cómo unirte a la red.\n\nDurante el período del programa CPT, los empleadores no asociados también pueden enviar roles específicos para participantes de CPT.',
    'index-events-kicker':   'Eventos',
    'index-events-h2':       'Encuéntranos en Persona',
    'index-events-intro':    'Conéctate con los consejeros de carrera de EJP y empleadores en próximos eventos.',
    'index-evt-1-h3':        'Feria de Carrera de Primavera',
    'index-evt-1-p':         'Fecha por confirmar — Lugar por confirmar',
    'index-evt-2-h3':        'Evento de Contratación en Salud',
    'index-evt-2-p':         'Fecha por confirmar — Lugar por confirmar',
    'index-evt-3-h3':        'Graduación CPT y Colocación',
    'index-evt-3-p':         'Fecha por confirmar — Lugar por confirmar',
    'index-evt-4-h3':        'Taller de Currículum',
    'index-evt-4-p':         'Fecha por confirmar — Lugar por confirmar',
    'index-events-btn':      'Ver Todos los Eventos →',
    'index-contact-h2':      'Contacto / Obtener Ayuda',
    'index-contact-intro':   'Estamos aquí para ayudar. Comunícate con el equipo adecuado.',
    'index-contact-1-h3':    'Consultas de Buscadores de Empleo',
    'index-contact-1-p':     'Preguntas sobre servicios de carrera, ayuda con currículum o cómo empezar',
    'index-contact-1-btn':   'Contactar Servicios de Carrera',
    'index-contact-2-h3':    'Consultas de Empleadores',
    'index-contact-2-p':     'Interesado en contratar o asociarse con EJP',
    'index-contact-2-btn':   'Contactar Relaciones con Empleadores',
    'index-contact-3-h3':    'Consultas de Alianzas',
    'index-contact-3-p':     'Conviértete en una organización comunitaria o socio proveedor',
    'index-contact-3-btn':   'Contactar Alianzas',
    // ── job-seekers.html ──────────────────────────────────────────
    'js-hero-h1':            'Tu Próximo Paso en Salud Comienza Aquí',
    'js-hero-p':             'Explora ofertas de empleo de cientos de instalaciones asociadas y envía tu currículum para ingresar al grupo de candidatos de EJP. Cuando surge una vacante, buscamos quién es el mejor candidato.',
    'js-kicker-get-started': 'Comenzar',
    'js-wizard-h2':          'Dinos Quién Eres',
    'js-wizard-intro':       'Déjanos saber quién eres para poder dirigirte mejor.',
    'js-wizard-jobs-h3':     'No Soy Participante de CPT',
    'js-wizard-jobs-p':      'Explora puestos de salud disponibles y envía tu currículum a empleadores en toda Nueva York. Se te notificará cuando los empleadores publiquen roles que coincidan con tus cualificaciones y criterios de búsqueda.',
    'js-wizard-cpt-p':       '¿Actualmente inscrito o completando el programa de Capacitación en Carreras Profesionales? Accede a recursos y apoyo dedicados para tu futura carrera en salud.',
    'js-wizard-mytef-callout': '¿Ya eres miembro de 1199? Inicia sesión en myTEF para apoyo de carrera →',
    'js-wizard-back':        '← Atrás',
    'js-wizard-member-h3':   'Soy Miembro del Sindicato',
    'js-wizard-member-sub':  'Incluyendo graduados de CPT',
    'js-wizard-member-p':    'Conéctate con un consejero de carrera que puede ayudar con colocación, asesoramiento y más.',
    'js-wizard-member-btn':  'Obtener Apoyo de Carrera →',
    'js-wizard-nonmember-h3':  'No Soy Miembro del Sindicato',
    'js-wizard-nonmember-p':   'Conoce los beneficios de la membresía en 1199SEIU y cómo acceder a los servicios de carrera.',
    'js-wizard-nonmember-btn': 'Más Información →',
    'js-wizard-browse-h3':   'Explorar Puestos Disponibles',
    'js-wizard-browse-p':    'Busca vacantes de salud y envía tu currículum directamente a los empleadores.',
    'js-wizard-browse-btn':  'Ver Empleos →',
    'js-form-member-h3':     'Te conectamos con los servicios de carrera',
    'js-form-member-p':      'Completa el formulario y un consejero de carrera te contactará para empezar.',
    'js-label-first-name':   'Nombre',
    'js-label-last-name':    'Apellido',
    'js-label-email':        'Correo Electrónico',
    'js-label-phone':        'Teléfono',
    'js-label-member-status':  'Estado de Membresía',
    'js-radio-active-member':  'Miembro Activo del Sindicato',
    'js-radio-cpt-grad':       'Graduado de CPT',
    'js-label-support-type':   '¿Qué tipo de apoyo buscas?',
    'js-checkbox-resume':      'Ayuda con Currículum',
    'js-checkbox-counseling':  'Asesoramiento de Carrera',
    'js-checkbox-interview':   'Preparación para Entrevistas',
    'js-checkbox-placement':   'Colocación / Emparejamiento de Empleo',
    'js-checkbox-workshop':    'Taller / Capacitación',
    'js-btn-connect':          'Conectarme con un Consejero →',
    'js-form-nonmember-h3':    'Estás en el lugar correcto',
    'js-form-nonmember-p':     'Deja tu correo y te enviaremos información sobre cómo acceder a los servicios de carrera — no necesitas membresía para comenzar.',
    'js-label-what-brought':   '¿Qué te trajo aquí?',
    'js-opt-select-one':       '-- Selecciona una opción --',
    'js-opt-looking-job':      'Estoy buscando un empleo en salud',
    'js-opt-training':         'Quiero explorar programas de capacitación',
    'js-opt-heard':            'Escuché sobre 1199SEIU y quiero saber más',
    'js-opt-other':            'Otro',
    'js-btn-send-info':        'Enviarme Más Información →',
    'js-btn-skip':             'Saltar — solo mostrarme lo disponible →',
    'js-benefits-kicker':      'Por qué unirse a 1199SEIU',
    'js-benefits-h2':          'El Poder de una Carrera con 1199',
    'js-benefits-intro':       'Con más de 450,000 miembros fuertes, los trabajadores de 1199 negocian juntos contratos sólidos que garantizan un salario justo, buenos beneficios y oportunidades educativas mientras lideran la lucha por apoyar a los trabajadores en todo Estados Unidos.',
    'js-svc-wages-h3':         'Salarios Dignos',
    'js-svc-wages-p':          'Los miembros de 1199 han ganado algunas de las mejores compensaciones del país, incluyendo aumentos anuales garantizados, mejor pago por guardia y más.',
    'js-svc-ladders-h3':       'Escaleras Profesionales',
    'js-svc-ladders-p':        'Los miembros elegibles de 1199SEIU tienen acceso a fondos de capacitación y educación para avanzar en sus carreras, obtener nuevas credenciales o mantener las certificaciones y licencias que ya poseen.',
    'js-svc-protections-h3':   'Protecciones para Trabajadores',
    'js-svc-protections-p':    'Los miembros de 1199 han ganado protecciones laborales como la prohibición de subcontratación, procesos disciplinarios más justos, proporciones específicas de trabajador-paciente y seguridad de jubilación mientras aprovechan nuestra fuerza colectiva para evitar despidos.',
    'js-svc-benefits-h3':      'Beneficios de Salud',
    'js-svc-benefits-p':       'Los miembros elegibles de 1199, tanto a tiempo completo como parcial, tienen acceso a seguro de salud de bajo costo o sin costo para ellos y sus familias.',
    'js-member-btn-login':     '¿Ya eres miembro? Inicia sesión en MyTEF →',
    'js-member-btn-browse':    'Ver Puestos Disponibles →',
    'js-mytef-h2':             'Portal MyTEF',
    'js-mytef-intro':          'Tu centro de capacitación y empleo — gestiona tus herramientas de desarrollo profesional en un solo lugar.',
    'js-mytef-f1-h3':          'Inscríbete en Clases',
    'js-mytef-f1-p':           'Explora e inscríbete en programas de capacitación disponibles',
    'js-mytef-f2-h3':          'Solicita Programas',
    'js-mytef-f2-p':           'Envía solicitudes para oportunidades de avance profesional',
    'js-mytef-f3-h3':          'Sube tu Currículum',
    'js-mytef-f3-p':           'Mantén tu currículum en archivo para emparejamiento con empleadores',
    'js-mytef-f4-h3':          'Consulta Reembolsos',
    'js-mytef-f4-p':           'Verifica el estado de tus reembolsos de matrícula y gastos',
    'js-mytef-login-btn':      'Iniciar Sesión en el Portal MyTEF →',
    // ── cpt.html ─────────────────────────────────────────────────
    'cpt-hero-h1':           'Crea Tu Cuenta de iCIMS',
    'cpt-hero-p':            'Como participante de CPT, tienes acceso a servicios de carrera dedicados incluyendo asistencia con currículum, asesoramiento de carrera, preparación para entrevistas y apoyo de colocación laboral. Para comenzar, crea tu cuenta de iCIMS.',
    'cpt-services-kicker':   'Tus Servicios de Carrera',
    'cpt-services-h2':       'Lo Que Está Disponible Para Ti',
    'cpt-svc-resume-h3':     'Asistencia con Currículum',
    'cpt-svc-resume-p':      'Obtén ayuda para crear un currículum profesional que destaque tu capacitación, experiencia y fortalezas.',
    'cpt-svc-counseling-h3': 'Asesoramiento de Carrera',
    'cpt-svc-counseling-p':  'Trabaja con un consejero dedicado para identificar tus metas, explorar opciones y construir un plan.',
    'cpt-svc-interview-h3':  'Preparación para Entrevistas',
    'cpt-svc-interview-p':   'Practica entrevistas, recibe retroalimentación y desarrolla la confianza para causar una buena impresión.',
    'cpt-svc-placement-h3':  'Apoyo de Colocación',
    'cpt-svc-placement-p':   'Conéctate con empleadores que buscan profesionales de salud calificados a través de nuestra red.',
    'cpt-svc-workshops-h3':  'Talleres y Desarrollo de Habilidades',
    'cpt-svc-workshops-p':   'Únete a sesiones grupales sobre estrategias de búsqueda de empleo, desarrollo profesional y preparación laboral.',
    'cpt-cta-h2':            'Comienza con iCIMS',
    'cpt-cta-p':             'Crea tu perfil de iCIMS para conectarte con nuestro equipo de reclutamiento y acceder a tus servicios de carrera.',
    'cpt-cta-signup':        'Crea Tu Perfil de iCIMS →',
    'cpt-cta-login':         '¿Ya tienes cuenta? Inicia sesión →',
    'cpt-expect-kicker':     'Qué Esperar',
    'cpt-expect-h2':         'Preguntas Frecuentes',
    'cpt-faq-q1':            '¿Cuál es la diferencia entre MyTEF e iCIMS?',
    'cpt-faq-a1':            'MyTEF es tu portal para acceder a servicios de carrera mientras que iCIMS es tu portal para acceder a empleos y ver lo que está disponible.',
    'cpt-faq-q2':            '¿Cómo contacto al personal de CPT con una pregunta?',
    'cpt-faq-a2':            'Usa la sección de Comentarios de Caso en MyTEF para comunicarte con el personal de CPT directamente. Puedes preguntar sobre elegibilidad, envío de documentos o el estado de tu cuenta.',
    'cpt-faq-q3':            '¿Puedo acceder a ayuda y orientación en persona?',
    'cpt-faq-a3':            'Sí, el Laboratorio Digital de Acceso Libre es un recurso gratuito donde puedes obtener apoyo práctico con tu búsqueda de empleo, currículum y herramientas de servicios de carrera.',
    'cpt-training-link-p':   '¿Buscas información sobre el programa de capacitación CPT?',
    'cpt-training-link-btn': 'Visita el Sitio de Capacitación CPT →',
    // ── employers.html ────────────────────────────────────────────
    'emp-hero-h1':           'Construya una Fuerza Laboral de Salud Calificada',
    'emp-hero-p':            'El Centro de Empleo y Ubicación Laboral se asocia con empleadores de salud en toda Nueva York para apoyar sus necesidades de reclutamiento al conectarlos con candidatos calificados.',
    'emp-why-h2':            'Por Qué Asociarte con EJP',
    'emp-why-intro':         'Como parte de la red de socios de EJP, los empleadores de salud reciben apoyo de reclutamiento dedicado y acceso directo a una cartera de graduados recientes listos para cubrir puestos vacantes.',
    'emp-svc-cpt-h3':        'Más de 7,000 Graduados de CPT',
    'emp-svc-cpt-p':         'Accede a una cartera de graduados recientes capacitados en una variedad de ocupaciones de salud — desde enfermería y salud aliada hasta roles técnicos y administrativos.',
    'emp-svc-screened-h3':   'Pre-Seleccionados y Preparados',
    'emp-svc-screened-p':    'Nuestros candidatos han completado capacitación, recibido asesoramiento de carrera y están listos para trabajar. No son solicitantes sin experiencia — son profesionales motivados.',
    'emp-svc-partner-h3':    'Alianza Continua',
    'emp-svc-partner-p':     'EJP no es un servicio de una sola vez. Construimos relaciones duraderas con empleadores para apoyar las necesidades continuas de personal y desarrollo de la fuerza laboral.',
    'emp-how-h2':            'Cómo Trabajar con Nosotros',
    'emp-vacancies-h3':      'Enviar Vacantes de Empleo',
    'emp-vacancies-p':       'Publica tus vacantes directamente a nuestro grupo de candidatos calificados.',
    'emp-vacancies-btn':     'Enviar una Vacante →',
    'emp-partner-h3':        'Convertirte en Proveedor Asociado',
    'emp-partner-p':         'Recibe apoyo de reclutamiento dedicado y acceso a la cartera de graduados recientes de EJP.',
    'emp-partner-link':      'Solicitar ser Socio →',
    'emp-events-h3':         'Asistir a Eventos de Contratación',
    'emp-events-p':          'Conoce candidatos calificados en persona en nuestras ferias de carrera y eventos de contratación en toda Nueva York.',
    'emp-events-link':       'Ver Próximos Eventos →',
    'emp-contact-h3':        'Contactar Relaciones con Empleadores',
    'emp-contact-p':         '¿Tienes preguntas sobre asociarte con EJP? Nuestro equipo de relaciones con empleadores está aquí para ayudar.',
    'emp-contact-link':      'Ponerse en Contacto →',
    'emp-stats-h2':          'En Números',
    'emp-stat-1-h3':         'Candidatos Capacitados',
    'emp-stat-1-p':          'Participantes de CPT listos para carreras en salud',
    'emp-stat-2-h3':         'Ocupaciones',
    'emp-stat-2-p':          'En enfermería, técnica y salud aliada',
    'emp-stat-3-h3':         'Tasa de Colocación',
    'emp-stat-3-p':          'Dato por confirmar',
    'emp-stat-4-h3':         'Empleadores Asociados',
    'emp-stat-4-p':          'Dato por confirmar',
    'emp-vacancy-modal-h2':  'Cuéntanos sobre tu Vacante',
    'emp-vacancy-modal-p':   'Envía los detalles de tu vacante y nuestro equipo de relaciones con empleadores te contactará pronto.',
    'emp-label-org':         'Nombre de la Organización',
    'emp-label-your-name':   'Tu Nombre',
    'emp-label-job-title':   'Título del Puesto / Tu Rol',
    'emp-label-work-email':  'Correo de Trabajo',
    'emp-label-phone':       'Teléfono',
    'emp-label-role-type':   'Tipo de Puesto Necesario',
    'emp-opt-select':        '-- Seleccionar --',
    'emp-label-openings':    'Número de Vacantes',
    'emp-label-notes':       'Notas Adicionales',
    'emp-checkbox-hiring':   '¿Interesado en asistir a un evento de contratación?',
    'emp-btn-submit':        'Enviar Vacante →',
    'emp-contact-modal-h2':  'Contactar Relaciones con Empleadores',
    'emp-contact-modal-p':   '¿Tienes una pregunta sobre asociarte con EJP? Te responderemos pronto.',
    'emp-label-first':       'Nombre',
    'emp-label-last':        'Apellido',
    'emp-label-org2':        'Organización',
    'emp-label-message':     '¿Cómo podemos ayudar?',
    'emp-btn-send':          'Enviar Mensaje →',
    'emp-placeholder-name':  'Nombre y apellido',
    // ── events.html ───────────────────────────────────────────────
    'evt-hero-h1':           'Eventos y Ferias de Carrera',
    'evt-hero-p':            'Conoce a los consejeros de carrera de EJP y a los empleadores del sector salud en persona. Desde ferias de carrera hasta talleres de currículum, nuestros eventos están diseñados para ayudarte a dar el siguiente paso.',
    'evt-kicker':            'Próximos',
    'evt-h2':                'Próximos Eventos',
    'evt-intro':             'Conéctate con empleadores y consejeros de carrera en nuestros próximos eventos en Nueva York.',
    'evt-month-jun':         'Jun',
    'evt-month-jul-1':       'Jul',
    'evt-month-jul-2':       'Jul',
    'evt-month-aug':         'Ago',
    'evt-1-h3':              'Feria de Carrera de Primavera 2026',
    'evt-1-p':               'Conoce empleadores del sector salud que contratan en enfermería, salud aliada y roles administrativos. Trae tu currículum y viste profesionalmente — entrevistas en el momento disponibles.',
    'evt-1-btn':             'Registrarse →',
    'evt-2-h3':              'Evento de Contratación en Salud',
    'evt-2-p':               'Un evento de contratación enfocado con empleadores asociados que buscan activamente candidatos capacitados en CPT. Se recomienda pre-registro.',
    'evt-2-btn':             'Registrarse →',
    'evt-3-h3':              'Taller de Currículum y Entrevistas',
    'evt-3-p':               'Únete a nuestros consejeros de carrera para un taller práctico sobre mejores prácticas de currículum, técnicas de entrevista y cómo destacarte ante empleadores del sector salud.',
    'evt-3-btn':             'RSVP →',
    'evt-4-h3':              'Ceremonia de Graduación y Colocación CPT',
    'evt-4-p':               'Celebra a los últimos graduados de CPT mientras hacen la transición a carreras en salud. Incluye networking con empleadores y anuncios de colocación.',
    'evt-4-btn':             'Más Información →',
    'evt-disclaimer':        'Detalles de registro próximamente. Las fechas y lugares están sujetos a cambios.',
    'evt-expect-h2':         'Qué Esperar en Nuestros Eventos',
    'evt-expect-intro':      'Ya seas graduado de CPT, miembro del sindicato o nuevo en el sector salud — nuestros eventos están diseñados para ayudarte a conectar, prepararte y avanzar.',
    'evt-exp-1-h3':          'Conoce Empleadores',
    'evt-exp-1-p':           'Conéctate directamente con organizaciones de salud que contratan en toda Nueva York. Muchas de nuestras ferias de carrera incluyen entrevistas en el momento.',
    'evt-exp-2-h3':          'Obtén Apoyo de Carrera',
    'evt-exp-2-p':           'Nuestros consejeros de carrera asisten a cada evento para ofrecer revisiones de currículum, orientación y apoyo individual.',
    'evt-exp-3-h3':          'Construye tu Red',
    'evt-exp-3-p':           'Conoce a otros buscadores de empleo, aprende de quienes ya han conseguido trabajo y forma parte de una comunidad comprometida con tu éxito.',
    'evt-employer-h2':       '¿Eres un Empleador?',
    'evt-employer-p':        'Participa en nuestras ferias de carrera y eventos de contratación para conocer candidatos calificados capacitados en CPT.',
    'evt-employer-btn':      'Asóciate con EJP →',
    'evt-modal-h2':          'Registrarse para Este Evento',
    'evt-label-first':       'Nombre',
    'evt-label-last':        'Apellido',
    'evt-label-email':       'Correo Electrónico',
    'evt-label-phone':       'Teléfono',
    'evt-label-member-q':    '¿Eres miembro del sindicato?',
    'evt-radio-yes-member':  'Sí — miembro de 1199SEIU',
    'evt-radio-yes-cpt':     'Sí — graduado de CPT',
    'evt-radio-no':          'No — aún no soy miembro',
    'evt-radio-not-sure':    'No estoy seguro/a',
    'evt-label-occupation':  '¿En qué ocupación estás interesado/a?',
    'evt-opt-select':        '-- Selecciona una opción --',
    'evt-opt-figuring':      'Aún lo estoy decidiendo',
    'evt-btn-register':      'Completar Registro →',
    // ── why-join.html ─────────────────────────────────────────────
    'wj-hero-h1':            '¿Por Qué Unirse a 1199SEIU?',
    'wj-hero-p':             'Entendemos que el sector salud no es solo un trabajo, sino a menudo una vocación. Como miembro del sindicato, obtienes el apoyo de carrera, capacitación y recursos para convertir esa vocación en una carrera duradera.',
    'wj-benefits-kicker':    'Beneficios de membresía',
    'wj-benefits-h2':        'Lo Que Obtienes como Miembro del Sindicato',
    'wj-benefits-intro':     'Los miembros de 1199SEIU y los graduados de CPT tienen acceso a una suite completa de servicios de carrera a través del Fondo de Capacitación y Empleo.',
    'wj-svc-counseling-h3':  'Asesoramiento de Carrera Dedicado',
    'wj-svc-counseling-p':   'Trabaja uno a uno con un consejero experimentado que te ayuda a establecer metas, explorar opciones y construir un plan para tu carrera.',
    'wj-svc-resume-h3':      'Apoyo con Currículum y Entrevistas',
    'wj-svc-resume-p':       'Obtén ayuda profesional para crear tu currículum y prepararte para entrevistas para causar una buena impresión.',
    'wj-svc-placement-h3':   'Colocación y Emparejamiento Laboral',
    'wj-svc-placement-p':    'Conéctate con empleadores del sector salud que buscan candidatos calificados a través de la red de empleadores de EJP.',
    'wj-svc-training-h3':    'Capacitación y Desarrollo de Habilidades',
    'wj-svc-training-p':     'Accede a talleres, programas de desarrollo profesional y capacitación para el avance de carrera a través del Fondo.',
    'wj-svc-mytef-h3':       'Acceso al Portal MyTEF',
    'wj-svc-mytef-p':        'Gestiona tu desarrollo profesional en un solo lugar — inscríbete en clases, sube tu currículum, solicita programas y más.',
    'wj-svc-security-h3':    'Fondo de Seguridad Laboral',
    'wj-svc-security-p':     'Si alguna vez eres despedido, accede a asistencia de reempleo y servicios de carrera prioritarios para retomar el camino.',
    'wj-healthcare-kicker':  'La oportunidad',
    'wj-healthcare-h2':      '¿Por Qué el Sector Salud?',
    'wj-healthcare-intro':   'La industria de salud de Nueva York es uno de los sectores más grandes y de más rápido crecimiento del estado.',
    'wj-hc-1-h3':            'Demanda Creciente',
    'wj-hc-1-p':             'Se proyecta que los empleos en salud crezcan significativamente en los próximos años, con miles de nuevas posiciones abriéndose en Nueva York.',
    'wj-hc-2-h3':            'Trabajo Significativo',
    'wj-hc-2-p':             'Las carreras en salud ofrecen la oportunidad de hacer una diferencia real en la vida de las personas todos los días — es un trabajo que importa.',
    'wj-hc-3-h3':            'Avance Profesional',
    'wj-hc-3-p':             'Con la capacitación y el apoyo adecuados, el sector salud ofrece caminos claros de crecimiento — desde puestos de nivel inicial hasta posiciones especializadas.',
    'wj-hc-4-h3':            'Estabilidad y Beneficios',
    'wj-hc-4-p':             'Los empleos sindicales en salud ofrecen salarios competitivos, beneficios integrales y seguridad a largo plazo que otras industrias no pueden igualar.',
    'wj-newsletter-h2':      'Mantente Conectado',
    'wj-newsletter-p':       '¿No listo para unirte todavía? Suscríbete a nuestro boletín para recibir actualizaciones sobre carreras en salud, eventos y oportunidades.',
    'wj-newsletter-btn':     'Suscribirse',
    'wj-newsletter-disclaimer': 'Respetamos tu privacidad. Cancela la suscripción en cualquier momento.',
    'wj-cta-h2':             '¿Listo para Dar el Siguiente Paso?',
    'wj-cta-p':              'Ya sea que estés buscando trabajo o quieras construir una carrera a largo plazo, EJP está aquí para ayudar.',
    'wj-cta-btn-primary':    'Explorar Servicios de Carrera →',
    'wj-cta-btn-secondary':  'Ver Empleos Disponibles →',
    'wj-placeholder-first':  'Nombre',
    'wj-placeholder-email':  'Tu correo electrónico',
    // ── thank-you.html ────────────────────────────────────────────
    'ty-h1':                 'Todo Listo',
    'ty-p1':                 'Gracias por comunicarte. Un miembro del equipo de EJP te dará seguimiento pronto.',
    'ty-card-1-h3':          'Ver Empleos Disponibles',
    'ty-card-1-p':           'Explora las vacantes actuales en empleadores asociados de 1199SEIU.',
    'ty-card-2-h3':          'Ver Próximos Eventos',
    'ty-card-2-p':           'Ferias de carrera, talleres y eventos de contratación cerca de ti.',
    'ty-card-3-h3':          'Conoce los Beneficios de Membresía',
    'ty-card-3-p':           'Ve todos los beneficios disponibles para los miembros de 1199SEIU.',
    'ty-disclaimer':         'Si enviaste un registro de evento, recibirás un correo de confirmación más cerca de la fecha del evento.',
    'ty-personalized':       'Hemos guardado tu información, {name}.',
    // ── Inline form success (showFormSuccess) ─────────────────────
    'form-success-heading':  'Todo listo',
    'success-newsletter':    'Te has suscrito. Te mantendremos informado sobre carreras en salud y eventos de EJP.',
    'success-vacancy':       'Gracias, {name}. Nuestro equipo de relaciones con empleadores se comunicará pronto.',
    'success-emp-contact':   'Mensaje recibido, {name}. Nos comunicaremos pronto.',
    'success-event':         '¡Estás registrado/a, {name}! Te enviaremos los detalles de confirmación más cerca del evento.',
  };

  // Captured English strings (populated from DOM before first translation).
  var _en = {};
  var _enPh = {};

  function capture() {
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n');
      if (!_en[key]) _en[key] = el.textContent;
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-placeholder');
      if (!_enPh[key]) _enPh[key] = el.placeholder;
    });
  }

  function applyTranslations(lang) {
    var isEs = lang === 'es';

    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n');
      var val = isEs ? es[key] : _en[key];
      if (val !== undefined) el.textContent = val;
    });

    document.querySelectorAll('[data-i18n-placeholder]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-placeholder');
      var val = isEs ? es[key] : _enPh[key];
      if (val !== undefined) el.placeholder = val;
    });

    // Update <html lang> for screen readers
    document.documentElement.lang = lang;

    // Toggle button label
    document.querySelectorAll('.js-lang-toggle').forEach(function (btn) {
      btn.textContent = isEs ? 'English' : 'Español';
    });
  }

  function getLang() {
    try { return localStorage.getItem('ejp_lang') || 'en'; } catch (e) { return 'en'; }
  }

  function init() {
    capture();
    var lang = getLang();
    if (lang === 'es') applyTranslations('es');

    document.addEventListener('click', function (e) {
      var btn = e.target.closest('.js-lang-toggle');
      if (!btn) return;
      e.preventDefault();
      var next = getLang() === 'es' ? 'en' : 'es';
      try { localStorage.setItem('ejp_lang', next); } catch (e) {}
      applyTranslations(next);
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
